#!/usr/bin/env python3
import json
import os

TEMPLATES_DIR = "templates"
os.makedirs(TEMPLATES_DIR, exist_ok=True)

def save_template(name, data):
    filename = os.path.join(TEMPLATES_DIR, f"{name}.json")
    with open(filename, "w") as f:
        json.dump(data, f, indent=2)
    print(f"✅ Template guardado: {filename}")

# --- FASE 6: TRUST CARDS ---
f6 = [{"id":"f6","elType":"section","settings":{"padding":{"unit":"px","top":0,"right":0,"bottom":60,"left":0}},"elements":[{"id":"c1","elType":"column","settings":{"_column_size":100},"elements":[{"id":"w1","elType":"widget","widgetType":"html","settings":{"html":"<style>.trust-grid-rehace{display:grid;grid-template-columns:repeat(4,1fr);max-width:1280px;margin:-50px auto 0;background:white;border-radius:12px;box-shadow:0 12px 48px rgba(0,51,102,0.12);overflow:hidden;position:relative;z-index:10}.trust-col-rehace{display:flex;flex-direction:column;align-items:center;text-align:center;gap:1rem;padding:3rem 1.5rem;border-right:1px solid #E8EEF5;transition:background 0.3s ease}.trust-col-rehace:last-child{border-right:none}.trust-col-rehace:hover{background:#F4F7FB}.trust-icon-wrap{width:56px;height:56px;border-radius:50%;background:rgba(1,164,190,0.1);display:flex;align-items:center;justify-content:center;color:#01A4BE;font-size:1.5rem}.trust-col-rehace h3{font-family:'Outfit',sans-serif;font-weight:700;font-size:1.1rem;color:#003366;margin:0}.trust-col-rehace p{font-family:'Figtree',sans-serif;font-size:0.9rem;color:#6B7E96;margin:0;line-height:1.5}</style><div class='trust-grid-rehace'><div class='trust-col-rehace'><div class='trust-icon-wrap'><i class='fas fa-brain'></i></div><h3>Especialidad Neuro</h3><p>Expertos en daño cerebral, ictus y parkinson.</p></div><div class='trust-col-rehace'><div class='trust-icon-wrap'><i class='fas fa-house-user'></i></div><h3>Centro y Domicilio</h3><p>Nos adaptamos a tu comodidad y necesidad real.</p></div><div class='trust-col-rehace'><div class='trust-icon-wrap'><i class='fas fa-hand-holding-medical'></i></div><h3>Valoración Gratuita</h3><p>Ven a conocernos y evaluaremos tu caso sin compromiso.</p></div><div class='trust-col-rehace'><div class='trust-icon-wrap'><i class='fas fa-users'></i></div><h3>Apoyo Integral</h3><p>Acompañamos al paciente y a toda su familia.</p></div></div>"}}]}]}]

# --- FASE 7: ESPECIALIDADES (RESUMEN) ---
f7 = [{"id":"f7","elType":"section","settings":{"padding":{"unit":"px","top":100,"right":0,"bottom":100,"left":0},"background_background":"classic","background_color":"#F4F7FB"},"elements":[{"id":"c2","elType":"column","settings":{"_column_size":100},"elements":[{"id":"w2","elType":"widget","widgetType":"html","settings":{"html":"<div style='text-align:center;max-width:800px;margin:0 auto 4rem'><span class='hero-eyebrow-text'>Especialidades</span><h2 style=\"font-family:'Outfit',sans-serif;font-weight:900;font-size:3rem;color:#003366;margin-top:1rem;text-transform:uppercase\">¿Qué tratamos en REHACE?</h2></div><style>.specs-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:2rem;max-width:1280px;margin:0 auto}.spec-card{background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,51,102,0.06);border:1px solid #E8EEF5;transition:transform 0.3s}.spec-card:hover{transform:translateY(-8px);box-shadow:0 20px 48px rgba(0,51,102,0.12)}.spec-img{width:100%;height:200px;background:#eee;background-size:cover}.spec-content{padding:1.5rem}.spec-tag{font-family:'Outfit',sans-serif;font-size:0.7rem;font-weight:700;color:#01A4BE;text-transform:uppercase;letter-spacing:0.1em;display:block;margin-bottom:0.5rem}.spec-content h3{font-family:'Outfit',sans-serif;font-weight:800;font-size:1.2rem;color:#003366;margin:0}</style><div class='specs-grid'><div class='spec-card'><div class='spec-img' style='background-image:url(\"https://rehace.es/wp-content/uploads/2026/04/treatment_stroke.png\")'></div><div class='spec-content'><span class='spec-tag'>Neurología</span><h3>Ictus y Daño Cerebral</h3></div></div><div class='spec-card'><div class='spec-img' style='background-image:url(\"https://rehace.es/wp-content/uploads/2026/04/treatment_parkinson.png\")'></div><div class='spec-content'><span class='spec-tag'>Neurología</span><h3>Parkinson</h3></div></div><div class='spec-card'><div class='spec-img' style='background-image:url(\"https://rehace.es/wp-content/uploads/2026/04/treatment_cognitive.png\")'></div><div class='spec-content'><span class='spec-tag'>Neuropsicología</span><h3>Alzheimer y Demencias</h3></div></div><div class='spec-card'><div class='spec-img' style='background-image:url(\"https://rehace.es/wp-content/uploads/2026/04/therapy_session_physio.png\")'></div><div class='spec-content'><span class='spec-tag'>Fisioterapia</span><h3>Esclerosis Múltiple</h3></div></div></div>"}}]}]}]

# --- FASE 8: POR QUE ELEGIR (SPLIT) ---
f8 = [{"id":"f8","elType":"section","settings":{"padding":{"unit":"px","top":120,"right":0,"bottom":120,"left":0}},"elements":[{"id":"c3","elType":"column","settings":{"_column_size":100},"elements":[{"id":"w3","elType":"widget","widgetType":"html","settings":{"html":"<style>.why-container{display:flex;gap:5rem;max-width:1280px;margin:0 auto;align-items:center}.why-img-col{flex:1;position:relative}.why-content-col{flex:1}.main-img{width:100%;border-radius:24px;box-shadow:0 40px 80px rgba(0,0,0,0.1)}.badge-flotante{position:absolute;bottom:40px;right:-30px;background:#003366;color:white;padding:2rem;border-radius:16px;box-shadow:0 20px 40px rgba(0,51,102,0.3)}.badge-flotante span{display:block;font-family:'Outfit',sans-serif;font-weight:900;font-size:2.5rem;color:#01A4BE;line-height:1}.why-list{list-style:none;padding:0;margin:3rem 0}.why-list li{padding-left:2rem;border-left:3px solid #01A4BE;margin-bottom:2rem;font-family:'Figtree',sans-serif}.why-list li strong{display:block;font-family:'Outfit',sans-serif;color:#003366;font-size:1.2rem}</style><div class='why-container'><div class='why-img-col'><img src='https://rehace.es/wp-content/uploads/2026/04/rehab_center_modern.png' class='main-img'><div class='badge-flotante'><span>+500</span><p>Pacientes tratados</p></div></div><div class='why-content-col'><span class='hero-eyebrow-text'>Más que una clínica</span><h2 style=\"font-family:'Outfit',sans-serif;font-weight:900;font-size:3.2rem;color:#003366;margin-top:1rem;line-height:1.1\">¿Por qué elegir REHACE?</h2><ul class='why-list'><li><strong>Equipo Multidisciplinar</strong><span>Trabajamos de forma coordinada por tu meta.</span></li><li><strong>Tratamiento Personalizado</strong><span>Diseñamos un plan basado en tu situación real.</span></li><li><strong>Reevaluación Continua</strong><span>Medimos cada paso para asegurar el progreso.</span></li></ul><a href='#' class='btn-rehace-primary'>Conoce a nuestro equipo</a></div></div>"}}]}]}]

# --- FASE 9: 4 PASOS ---
f9 = [{"id":"f9","elType":"section","settings":{"padding":{"unit":"px","top":120,"right":0,"bottom":120,"left":0},"background_background":"classic","background_color":"#F4F7FB"},"elements":[{"id":"c4","elType":"column","settings":{"_column_size":100},"elements":[{"id":"w4","elType":"widget","widgetType":"html","settings":{"html":"<style>.steps-card-rehace{background:white;border-radius:24px;box-shadow:0 30px 90px rgba(0,51,102,.12);overflow:hidden;margin:4rem auto 0;max-width:1280px}.steps-grid-rehace{display:grid;grid-template-columns:repeat(4,1fr)}.step-col{padding:4rem 3rem;border-right:1px solid #E8EEF5;position:relative;transition:background 0.3s}.step-col:last-child{border-right:none}.step-col:hover{background:#F9FBFD}.step-n{font-family:'Outfit',sans-serif;font-weight:900;font-size:5rem;line-height:1;margin-bottom:2rem;color:#003366;opacity:0.1;display:block}.step-col h3{font-family:'Outfit',sans-serif;font-size:1.25rem;font-weight:800;margin-bottom:1rem;color:#003366}.step-col p{font-family:'Figtree',sans-serif;font-size:.95rem;line-height:1.6;color:#6B7E96}.steps-cta-rehace{border-top:1px solid #E8EEF5;padding:2.5rem 3.5rem;display:flex;align-items:center;justify-content:space-between;background:#fafafa}.steps-cta-rehace p{font-family:'Figtree',sans-serif;font-size:1.1rem;color:#003366;font-weight:600;margin:0}</style><div style='text-align:center;max-width:800px;margin:0 auto'><span class='hero-eyebrow-text'>El Camino</span><h2 style=\"font-family:'Outfit',sans-serif;font-weight:900;font-size:3.2rem;color:#003366;margin-top:1.5rem;text-transform:uppercase\">Tu Recuperación en 4 Pasos</h2></div><div class='steps-card-rehace'><div class='steps-grid-rehace'><div class='step-col'><span class='step-n'>01</span><h3>Valoración</h3><p>Evaluamos tu situación sin compromiso.</p></div><div class='step-col'><span class='step-n'>02</span><h3>Objetivos</h3><p>Establecemos metas conjuntas reales.</p></div><div class='step-col'><span class='step-n'>03</span><h3>Terapia</h3><p>Puesta en marcha del plan multidisciplinar.</p></div><div class='step-col'><span class='step-n'>04</span><h3>Seguimiento</h3><p>Medimos y ajustamos hasta el éxito.</p></div></div><div class='steps-cta-rehace'><p>La valoración inicial es gratuita.</p><a href='#' class='btn-rehace-primary'>Pedir Cita</a></div></div>"}}]}]}]

if __name__ == "__main__":
    save_template("fase_6_trust_cards", f6)
    save_template("fase_7_especialidades", f7)
    save_template("fase_8_por_que_elegir", f8)
    save_template("fase_9_cuatro_pasos", f9)
